from rest_framework.generics import ListAPIView, RetrieveAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.status import HTTP_200_OK, HTTP_201_CREATED
from rest_framework.permissions import IsAuthenticated
